# Gen-1 Pokedex entries (Red flavor, trimmed) and catch locations.
DEX_ENTRY = {
    1: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.',
    2: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.',
    3: 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.',
    4: 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.',
    5: 'When it swings its burning tail, it elevates the temperature to unbearably high levels.',
    6: 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.',
    7: 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.',
    8: 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.',
    9: 'A brutal Pokemon with pressurized water jets on its shell. They are used for high speed tackles.',
    10: 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.',
    11: 'This Pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body.',
    12: 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.',
    13: 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.',
    14: 'Almost incapable of moving, this Pokemon can only harden its shell to protect itself from predators.',
    15: 'Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.',
    16: 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.',
    17: 'Very protective of its sprawling territorial area, this Pokemon will fiercely peck at any intruder.',
    18: 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.',
    19: 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.',
    20: 'It uses its whis kers to maintain its balance. It apparently slows down if they are cut off.',
    21: 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.',
    22: 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.',
    23: 'Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.',
    24: 'It is rumored that the ferocious warning markings on its belly differ from area to area.',
    25: 'When several of these Pokemon gather, their electricity could build and cause lightning storms.',
    26: 'Its long tail serves as a ground to protect itself from its own high voltage power.',
    27: 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.',
    28: 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.',
    29: 'Although small, its venomous barbs render this Pokemon dangerous. The female has smaller horns.',
    30: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
    31: 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.',
    32: 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.',
    33: 'An aggressive Pokemon that is quick to attack. The horn on its head secretes a powerful venom.',
    34: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.",
    35: 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.',
    36: 'A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people.',
    37: 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.',
    38: 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.',
    39: 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
    40: 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.',
    41: 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.',
    42: 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.',
    43: 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.',
    44: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.",
    45: 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.',
    46: 'Burrows to suck tree roots. The mushrooms on its back grow by draw ing nutrients from the bug host.',
    47: 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.',
    48: 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.',
    49: 'The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.',
    50: 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.',
    51: 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.',
    52: 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.',
    53: 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.',
    54: 'While lulling its enemies with its vacant look, this wily Pokemon will use psychokinetic powers.',
    55: 'Often seen swim ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.',
    56: 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.',
    57: 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.',
    58: 'Very protective of its territory. It will bark and bite to repel intruders from its space.',
    59: 'A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings.',
    60: 'Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.',
    61: 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.',
    62: 'An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.',
    63: 'Using its ability to read minds, it will identify impending danger and Teleport to safety.',
    64: 'It emits special alpha waves from its body that induce headaches just by being close by.',
    65: 'Its brain can out perform a super computer. Its intelligence quotient is said to be 5,000.',
    66: 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.',
    67: 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.',
    68: 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.',
    69: 'A carnivorous Pokemon that traps and eats bugs. It uses its root feet to soak up needed moisture.',
    70: 'It spits out Poisonpowder to immobilize the enemy and then finishes it with a spray of Acid.',
    71: 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.',
    72: 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.',
    73: 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.',
    74: 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.',
    75: 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.',
    76: 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.',
    77: 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.',
    78: 'Very competitive, this Pokemon will chase anything that moves fast in the hopes of racing it.',
    79: 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.',
    80: "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps.",
    81: 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.',
    82: 'Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.',
    83: 'The sprig of green onions it holds is its weapon. It is used much like a metal sword.',
    84: 'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.',
    85: 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.',
    86: 'The protruding horn on its head is very hard. It is used for bashing through thick ice.',
    87: 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.',
    88: 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.',
    89: 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.',
    90: 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.',
    91: 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.',
    92: 'Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice.',
    93: 'Because of its ability to slip through block walls, it is said to be from an other dimension.',
    94: 'Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright.',
    95: 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.',
    96: 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.',
    97: 'When it locks eyes with an enemy, it will use a mix of Psi moves such as Hypnosis and Confusion.',
    98: 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.',
    99: 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.',
    100: 'Usually found in power plants. Easily mistaken for a Poke Ball, they have zapped many people.',
    101: 'It stores electric energy under very high pressure. It often explodes with little or no provocation.',
    102: 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.',
    103: 'Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.',
    104: "Because it never removes its skull helmet, no one has ever seen this Pokemon's real face.",
    105: 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.',
    106: 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.',
    107: 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.',
    108: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.",
    109: 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.',
    110: 'Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a Weezing over many years.',
    111: 'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.',
    112: 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.',
    113: 'A rare and elusive Pokemon that is said to bring happiness to those who manage to get it.',
    114: 'The whole body is swathed with wide vines that are similar to sea weed. Its vines shake as it walks.',
    115: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old.",
    116: 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.',
    117: 'Capable of swim ming backwards by rapidly flapping its wing-like pectoral fins and stout tail.',
    118: 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.',
    119: 'In the autumn spawning season, they can be seen swimming power fully up rivers and creeks.',
    120: 'An enigmatic Pokemon that can effortlessly regenerate any appendage it loses in battle.',
    121: 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.',
    122: 'If interrupted while it is miming, it will slap around the offender with its broad hands.',
    123: 'With ninja-like agility and speed, it can create the illusion that there is more than one.',
    124: 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.',
    125: 'Normally found near power plants, they can wander away and cause major blackouts in cities.',
    126: 'Its body always burns with an orange glow that enables it to hide perfectly among flames.',
    127: 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.',
    128: 'When it targets an enemy, it charges furiously while whipping its body with its long tails.',
    129: 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.',
    130: 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.',
    131: 'A Pokemon that has been over hunted almost to extinction. It can ferry people across the water.',
    132: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy.",
    133: 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.',
    134: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.",
    135: 'It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts.',
    136: 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.',
    137: 'A Pokemon that consists entirely of programming code. Capable of moving freely in cyberspace.',
    138: 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.',
    139: 'A prehistoric Pokemon that died out when its heavy shell made it impossible to catch prey.',
    140: 'A Pokemon that was resurrected from a fossil found in what was once the ocean floor eons ago.',
    141: 'Its sleek shape is perfect for swim ming. It slashes prey with its claws and drains the body fluids.',
    142: "A ferocious, pre historic Pokemon that goes for the enemy's throat with its serrated saw-like fangs.",
    143: 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.',
    144: 'A legendary bird Pokemon that is said to appear to doomed people who are lost in icy mountains.',
    145: 'A legendary bird Pokemon that is said to appear from clouds while dropping enormous lightning bolts.',
    146: 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.',
    147: 'Long considered a mythical Pokemon until recently when a small colony was found living underwater.',
    148: 'A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions.',
    149: 'An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans.',
    150: 'It was created by a scientist after years of horrific gene splicing and Dna engineering experiments.',
    151: 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.',
}

CATCH_LOC = {
    1: 'Choose Bulbasaur as a starter from Professor Oak in Pallet Town.',
    2: 'Ivysaur is not found in the wild; obtain it by evolving its pre-evolution.',
    3: 'Venusaur is not found in the wild; obtain it by evolving its pre-evolution.',
    4: 'Choose Charmander as a starter from Professor Oak in Pallet Town.',
    5: 'Charmeleon is not found in the wild; obtain it by evolving its pre-evolution.',
    6: 'Charizard is not found in the wild; obtain it by evolving its pre-evolution.',
    7: 'Choose Squirtle as a starter from Professor Oak in Pallet Town.',
    8: 'Wartortle is not found in the wild; obtain it by evolving its pre-evolution.',
    9: 'Blastoise is not found in the wild; obtain it by evolving its pre-evolution.',
    10: 'Wild Caterpie appear in Route 2, Route 24, Route 25, and Viridian Forest.',
    11: 'Wild Metapod appear in Route 24, Route 25, and Viridian Forest.',
    12: 'Butterfree is not found in the wild; obtain it by evolving its pre-evolution.',
    13: 'Wild Weedle appear in Route 2, Route 24, Route 25, and Viridian Forest.',
    14: 'Wild Kakuna appear in Route 24, Route 25, and Viridian Forest.',
    15: 'Beedrill is not found in the wild; obtain it by evolving its pre-evolution.',
    16: 'Wild Pidgey appear in Route 12, Route 1, Route 2, and other Kanto areas.',
    17: 'Wild Pidgeotto appear in Route 12, Route 5, Route 6, and other Kanto areas.',
    18: 'Pidgeot is not found in the wild; obtain it by evolving its pre-evolution.',
    19: 'Wild Rattata appear in Route 1, Route 2, Route 3, and other Kanto areas.',
    20: 'Wild Raticate appear in Route 9, Route 10, Route 11, and other Kanto areas.',
    21: 'Wild Spearow appear in Route 3, Route 4, Route 9, and other Kanto areas.',
    22: 'Wild Fearow appear in Route 9, Route 16, Route 17, and other Kanto areas.',
    23: 'Wild Ekans appear in Route 4, Route 8, Route 9, and other Kanto areas.',
    24: 'Wild Arbok appear in Cerulean Cave and Route 23.',
    25: 'Pikachu appears in Viridian Forest. In Yellow it also appears at the Power Plant.',
    26: 'Wild Raichu appear in Cerulean Cave and Power Plant.',
    27: 'Wild Sandshrew appear in Mt. Moon, Route 3, Route 4, and other Kanto areas.',
    28: 'Wild Sandslash appear in Cerulean Cave and Route 23.',
    29: 'Wild Nidoran-F appear in Route 2, Route 9, Route 10, and other Kanto areas.',
    30: 'Wild Nidorina appear in Route 9, Route 11, Route 23, and other Kanto areas.',
    31: 'Nidoqueen is not found in the wild; obtain it by evolving its pre-evolution.',
    32: 'Wild Nidoran-M appear in Route 2, Route 9, Route 10, and other Kanto areas.',
    33: 'Wild Nidorino appear in Route 9, Route 23, Safari Zone, and other Kanto areas.',
    34: 'Nidoking is not found in the wild; obtain it by evolving its pre-evolution.',
    35: 'Wild Clefairy appear in Mt. Moon and Celadon Game Corner.',
    36: 'Clefable is not found in the wild; obtain it by evolving its pre-evolution.',
    37: 'Wild Vulpix appear in Route 7, Route 8, Pokemon Mansion, and other Kanto areas.',
    38: 'Ninetales is not found in the wild; obtain it by evolving its pre-evolution.',
    39: 'Wild Jigglypuff appear in Route 3, Route 5, Route 6, and other Kanto areas.',
    40: 'Wild Wigglytuff appear in Cerulean Cave and Celadon Game Corner.',
    41: 'Wild Zubat appear in Seafoam Islands and other Kanto areas.',
    42: 'Wild Golbat appear in Seafoam Islands and other Kanto areas.',
    43: 'Wild Oddish appear in Route 12, Route 5, Route 6, and other Kanto areas.',
    44: 'Wild Gloom appear in Route 12, Route 13, Route 14, and other Kanto areas.',
    45: 'Vileplume is not found in the wild; obtain it by evolving its pre-evolution.',
    46: 'Wild Paras appear in Mt. Moon and other Kanto areas.',
    47: 'Wild Parasect appear in Route 18, Cerulean Cave, and other Kanto areas.',
    48: 'Wild Venonat appear in Route 12, Route 13, Route 14, and other Kanto areas.',
    49: 'Wild Venomoth appear in Route 14, Route 15, Cerulean Cave, and other Kanto areas.',
    50: "Wild Diglett appear in Diglett's Cave.",
    51: "Wild Dugtrio appear in Route 11 and Diglett's Cave.",
    52: 'Wild Meowth appear in Route 5, Route 6, Route 7, and Route 8.',
    53: 'Persian is not found in the wild; obtain it by evolving its pre-evolution.',
    54: 'Wild Psyduck appear in Seafoam Islands and other Kanto areas.',
    55: 'Wild Golduck appear in Seafoam Islands and Route 6.',
    56: 'Wild Mankey appear in Route 3, Route 4, Route 5, and other Kanto areas.',
    57: 'Wild Primeape appear in Route 23.',
    58: 'Wild Growlithe appear in Route 7, Route 8, Pokemon Mansion, and other Kanto areas.',
    59: 'Arcanine is not found in the wild; obtain it by evolving its pre-evolution.',
    60: 'Wild Poliwag appear in Seafoam Islands, Route 12, and other Kanto areas.',
    61: 'Wild Poliwhirl appear in Celadon City, Route 10, Route 22, and Route 23.',
    62: 'Poliwrath is not found in the wild; obtain it by evolving its pre-evolution.',
    63: 'Wild Abra appear in Route 5, Route 6, Route 7, and other Kanto areas.',
    64: 'Wild Kadabra appear in Route 8 and Cerulean Cave.',
    65: 'Alakazam is not found in the wild; obtain it by evolving its pre-evolution.',
    66: 'Wild Machop appear in Rock Tunnel, Route 10, and other Kanto areas.',
    67: 'Wild Machoke appear in Victory Road and Underground Path.',
    68: 'Machamp is not found in the wild; obtain it by evolving its pre-evolution.',
    69: 'Wild Bellsprout appear in Route 12, Route 5, Route 6, and other Kanto areas.',
    70: 'Wild Weepinbell appear in Route 12, Route 13, Route 14, and other Kanto areas.',
    71: 'Victreebel is not found in the wild; obtain it by evolving its pre-evolution.',
    72: 'Wild Tentacool appear in Seafoam Islands, Route 12, and other Kanto areas.',
    73: 'Wild Tentacruel appear in Sea Route 19, Sea Route 20, and Sea Route 21.',
    74: 'Wild Geodude appear in Mt. Moon, Rock Tunnel, and other Kanto areas.',
    75: 'Wild Graveler appear in Cerulean Cave and other Kanto areas.',
    76: 'Golem is not found in the wild; obtain it by evolving its pre-evolution.',
    77: 'Wild Ponyta appear in Route 17, Pokemon Mansion, and other Kanto areas.',
    78: 'Rapidash is not found in the wild; obtain it by evolving its pre-evolution.',
    79: 'Wild Slowpoke appear in Seafoam Islands and other Kanto areas.',
    80: 'Wild Slowbro appear in Seafoam Islands and other Kanto areas.',
    81: 'Wild Magnemite appear in Route 10 and Power Plant.',
    82: 'Wild Magneton appear in Cerulean Cave and Power Plant.',
    83: "Wild Farfetch'd appear in Route 12, Vermilion City, and Route 13.",
    84: 'Wild Doduo appear in Route 16, Route 17, Route 18, and other Kanto areas.',
    85: 'Wild Dodrio appear in Route 17 and Cerulean Cave.',
    86: 'Wild Seel appear in Seafoam Islands and other Kanto areas.',
    87: 'Wild Dewgong appear in Seafoam Islands and Cinnabar Island lab.',
    88: 'Wild Grimer appear in Power Plant, Pokemon Mansion, and other Kanto areas.',
    89: 'Wild Muk appear in Power Plant, Pokemon Mansion, and other Kanto areas.',
    90: 'Wild Shellder appear in Seafoam Islands and other Kanto areas.',
    91: 'Cloyster is not found in the wild; obtain it by evolving its pre-evolution.',
    92: 'Wild Gastly appear in Pokemon Tower and other Kanto areas.',
    93: 'Wild Haunter appear in Pokemon Tower and other Kanto areas.',
    94: 'Gengar is not found in the wild; obtain it by evolving its pre-evolution.',
    95: 'Wild Onix appear in Rock Tunnel, Victory Road, and other Kanto areas.',
    96: 'Wild Drowzee appear in Route 11.',
    97: 'Wild Hypno appear in Cerulean Cave.',
    98: 'Wild Krabby appear in Seafoam Islands and other Kanto areas.',
    99: 'Wild Kingler appear in Seafoam Islands and other Kanto areas.',
    100: 'Wild Voltorb appear in Route 10 and Power Plant.',
    101: 'Wild Electrode appear in Cerulean Cave, Power Plant, and Cinnabar Island lab.',
    102: 'Wild Exeggcute appear in Safari Zone.',
    103: 'Exeggutor is not found in the wild; obtain it by evolving its pre-evolution.',
    104: 'Wild Cubone appear in Pokemon Tower and other Kanto areas.',
    105: 'Wild Marowak appear in Cerulean Cave, Victory Road, and other Kanto areas.',
    106: 'Wild Hitmonlee appear in Fighting Dojo in Saffron City.',
    107: 'Wild Hitmonchan appear in Fighting Dojo in Saffron City.',
    108: 'Wild Lickitung appear in Route 18 and Cerulean Cave.',
    109: 'Wild Koffing appear in Pokemon Mansion.',
    110: 'Wild Weezing appear in Pokemon Mansion.',
    111: 'Wild Rhyhorn appear in Cerulean Cave and Safari Zone.',
    112: 'Wild Rhydon appear in Cerulean Cave and Cinnabar Island lab.',
    113: 'Wild Chansey appear in Cerulean Cave, Safari Zone, and other Kanto areas.',
    114: 'Wild Tangela appear in Sea Route 21, Safari Zone, and Cinnabar Island lab.',
    115: 'Wild Kangaskhan appear in Safari Zone.',
    116: 'Wild Horsea appear in Seafoam Islands and other Kanto areas.',
    117: 'Wild Seadra appear in Seafoam Islands, Route 12, and other Kanto areas.',
    118: 'Wild Goldeen appear in Seafoam Islands, Route 12, and other Kanto areas.',
    119: 'Wild Seaking appear in Cerulean City, Fuchsia City, Route 24, and other Kanto areas.',
    120: 'Wild Staryu appear in Seafoam Islands and other Kanto areas.',
    121: 'Starmie is not found in the wild; obtain it by evolving its pre-evolution.',
    122: 'Wild Mr. Mime appear in Route 2.',
    123: 'Wild Scyther appear in Safari Zone and Celadon Game Corner.',
    124: 'Wild Jynx appear in Cerulean City.',
    125: 'Wild Electabuzz appear in Power Plant.',
    126: 'Wild Magmar appear in Pokemon Mansion and Pokemon Mansion.',
    127: 'Wild Pinsir appear in Safari Zone and other Kanto areas.',
    128: 'Wild Tauros appear in Safari Zone.',
    129: 'Wild Magikarp appear in Seafoam Islands, Route 12, and other Kanto areas.',
    130: 'Wild Gyarados appear in Fuchsia City.',
    131: 'Wild Lapras appear in Silph Co.',
    132: 'Wild Ditto appear in Route 13, Route 14, Route 15, and other Kanto areas.',
    133: 'Eevee is a gift in Celadon City. It cannot be caught wild in Red or Blue.',
    134: 'Vaporeon is not found in the wild; obtain it by evolving its pre-evolution.',
    135: 'Jolteon is not found in the wild; obtain it by evolving its pre-evolution.',
    136: 'Flareon is not found in the wild; obtain it by evolving its pre-evolution.',
    137: 'Wild Porygon appear in Celadon Game Corner.',
    138: 'Revive the Helix Fossil into Omanyte at the Cinnabar Island lab.',
    139: 'Evolve Omanyte into Omastar by leveling up.',
    140: 'Revive the Dome Fossil into Kabuto at the Cinnabar Island lab.',
    141: 'Evolve Kabuto into Kabutops by leveling up.',
    142: 'Revive Old Amber into Aerodactyl at the Cinnabar Island lab.',
    143: 'Snorlax blocks Route 12 and Route 16; wake it with the Poke Flute.',
    144: 'Articuno is found in the Seafoam Islands.',
    145: 'Zapdos is found in the Power Plant.',
    146: 'Moltres is found on Victory Road.',
    147: 'Wild Dratini appear in Safari Zone and other Kanto areas.',
    148: 'Wild Dragonair appear in Safari Zone.',
    149: 'Dragonite is not found in the wild in Kanto; obtain it by trade, gift, or a special event.',
    150: 'Mewtwo is found in Cerulean Cave becoming Champion.',
    151: 'Mew is a mythical Pokemon not normally found wild in Red, Blue, or Yellow.',
}
